name: Build and Sign VST3

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  macos-build-sign:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: |
          brew install cmake

      - name: Install vcpkg + dependencies
        run: |
          brew install vcpkg
          git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
          export VCPKG_ROOT="$HOME/vcpkg"
          vcpkg install

      - name: Configure and build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" --toolchain "$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build build --config Release

      - name: Decode and install certificate
        run: |
          security create-keychain -p slimegreenmachine build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p slimegreenmachine build.keychain
          echo "${{ secrets.MAC_CERT_P12 }}" | base64 --decode > cert.p12
          security import cert.p12 -k build.keychain -P "${{ secrets.MAC_CERT_PASSWORD }}" -T /usr/bin/codesign -A
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k slimegreenmachine build.keychain
          codesign --deep --force --options runtime \
            --sign "Developer ID Application: James Pickering (G34JXTX2UG)" \
            "build/real_human_bean_artefacts/Release/VST3/real human bean.vst3"

      - name: Notarize
        run: |
          ditto -c -k --keepParent \
            "build/real_human_bean_artefacts/Release/VST3/real human bean.vst3" \
            "real-human-bean.zip"
          xcrun notarytool submit "real-human-bean.zip" \
            --apple-id "${{ secrets.MAC_APPLE_ID }}" \
            --team-id "${{ secrets.MAC_TEAM_ID }}" \
            --password "${{ secrets.MAC_APP_PASSWORD }}" \
            --wait
          unzip -o real-human-bean.zip -d .

      - name: Staple ticket
        run: xcrun stapler staple "real human bean.vst3"

      - name: Re-zip for release
        run: ditto -c -k --keepParent "real human bean.vst3" real-human-bean-release.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: real-human-bean-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}